name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Log in to GHCR
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u bimalgandhi46 --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/bimalgandhi46/thunder-herd:latest .

      - name: Push Docker image
        run: docker push ghcr.io/bimalgandhi46/thunder-herd:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Run Ansible deploy
        run: |
          cd /home/githubrunner/ansible/ansible-cicd-springboot
          ansible-playbook -i inventory/hosts.ini playbooks/deploy.yml \
            --vault-password-file ~/.vault_pass.txt
